# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orion_mcp_tools.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orion_mcp_tools.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15orion_mcp_tools.proto\x12\x0corion.mcp.v1\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x12\n\x10ListToolsRequest\"\'\n\x11ListToolsResponse\x12\x12\n\ntool_names\x18\x01 \x03(\t\"6\n\x0eRunToolRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x11\n\targs_json\x18\x02 \x01(\t\"C\n\x0fRunToolResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x15\n\renvelope_json\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\xef\x01\n\x12\x41nalyticsServiceV1\x12\x43\n\x06Health\x12\x1b.orion.mcp.v1.HealthRequest\x1a\x1c.orion.mcp.v1.HealthResponse\x12L\n\tListTools\x12\x1e.orion.mcp.v1.ListToolsRequest\x1a\x1f.orion.mcp.v1.ListToolsResponse\x12\x46\n\x07RunTool\x12\x1c.orion.mcp.v1.RunToolRequest\x1a\x1d.orion.mcp.v1.RunToolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orion_mcp_tools_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=39
  _globals['_HEALTHREQUEST']._serialized_end=54
  _globals['_HEALTHRESPONSE']._serialized_start=56
  _globals['_HEALTHRESPONSE']._serialized_end=88
  _globals['_LISTTOOLSREQUEST']._serialized_start=90
  _globals['_LISTTOOLSREQUEST']._serialized_end=108
  _globals['_LISTTOOLSRESPONSE']._serialized_start=110
  _globals['_LISTTOOLSRESPONSE']._serialized_end=149
  _globals['_RUNTOOLREQUEST']._serialized_start=151
  _globals['_RUNTOOLREQUEST']._serialized_end=205
  _globals['_RUNTOOLRESPONSE']._serialized_start=207
  _globals['_RUNTOOLRESPONSE']._serialized_end=274
  _globals['_ANALYTICSSERVICEV1']._serialized_start=277
  _globals['_ANALYTICSSERVICEV1']._serialized_end=516
# @@protoc_insertion_point(module_scope)
