# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from orion_mcp.mcp_adapter.grpc_gen import orion_mcp_tools_pb2 as orion__mcp__tools__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orion_mcp_tools_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceV1Stub(object):
    """Contrato V1: alterações só aditivas; breaking → AnalyticsServiceV2.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/orion.mcp.v1.AnalyticsServiceV1/Health',
                request_serializer=orion__mcp__tools__pb2.HealthRequest.SerializeToString,
                response_deserializer=orion__mcp__tools__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/orion.mcp.v1.AnalyticsServiceV1/ListTools',
                request_serializer=orion__mcp__tools__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=orion__mcp__tools__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.RunTool = channel.unary_unary(
                '/orion.mcp.v1.AnalyticsServiceV1/RunTool',
                request_serializer=orion__mcp__tools__pb2.RunToolRequest.SerializeToString,
                response_deserializer=orion__mcp__tools__pb2.RunToolResponse.FromString,
                _registered_method=True)


class AnalyticsServiceV1Servicer(object):
    """Contrato V1: alterações só aditivas; breaking → AnalyticsServiceV2.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceV1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=orion__mcp__tools__pb2.HealthRequest.FromString,
                    response_serializer=orion__mcp__tools__pb2.HealthResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=orion__mcp__tools__pb2.ListToolsRequest.FromString,
                    response_serializer=orion__mcp__tools__pb2.ListToolsResponse.SerializeToString,
            ),
            'RunTool': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTool,
                    request_deserializer=orion__mcp__tools__pb2.RunToolRequest.FromString,
                    response_serializer=orion__mcp__tools__pb2.RunToolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orion.mcp.v1.AnalyticsServiceV1', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orion.mcp.v1.AnalyticsServiceV1', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsServiceV1(object):
    """Contrato V1: alterações só aditivas; breaking → AnalyticsServiceV2.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orion.mcp.v1.AnalyticsServiceV1/Health',
            orion__mcp__tools__pb2.HealthRequest.SerializeToString,
            orion__mcp__tools__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orion.mcp.v1.AnalyticsServiceV1/ListTools',
            orion__mcp__tools__pb2.ListToolsRequest.SerializeToString,
            orion__mcp__tools__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orion.mcp.v1.AnalyticsServiceV1/RunTool',
            orion__mcp__tools__pb2.RunToolRequest.SerializeToString,
            orion__mcp__tools__pb2.RunToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
